name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install dependencies and build
      run: yarn && yarn build

    - name: vuepress-deploy
      if: github.event_name == 'pull_request'
      uses: ./.github/actions/vuepress-build-and-deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: asf-site
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
        COMMIT_MESSAGE: Auto deploy from Github Actions
